SDL_DIR := $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))

SOURCES_C := $(shell find $(SDL_DIR)/src -name '*.c')

INCLUDES += -I$(SDL_DIR)/include

CFLAGS += -fpermissive -Wsign-compare
CXXFLAGS += -fpermissive -Wsign-compare